name: Build

on:
  push:
    branches: [ master ]

jobs:
  build_docs:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.3'
          extended: true

      - name: Build
        shell: pwsh
        run: |
          ./tasks.ps1 sync-content
          ./tasks.ps1 build

      - name: Set CNAME
        run: echo "rules.switzerlan.ch" > ./website/public/CNAME

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
